### PR TITLE
small typo

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by bruvv** [comment]
@buldogwtf reminder ;)

**Comment by bruvv** [comment]
why did you close it?

**Comment by buldogwtf** [comment]
changed:

delay(1000); >small delay for when te sensor stops at metal 

to:
    delay(1000); //small delay for when te sensor stops at metal

and 

      sensor_class: motion
      device_class: motion

**Comment by bruvv** [comment]
why not just merge it? Lol anyway thanks for the repo.

**Pull request closed without merging**
